### ISSUE TITLE
Error running TACI plugin

### ISSUE THREAD

**Issue by Eddymorphling** [niflylab/TACI_CalciumImagingPlugin#2]
Hello,
I would like to use TACI on TrackMate generated files that you just simply 2D+T datasets. 

I tried to do so by setting the Z=1 in the TrackMate7 generated csv files and running it along with the Background_list where I only include background intensity from one z plane. Then when I run the `extract` function in TACI I get an error and no output is generated. Would you mind helping me resolve this issue? I would be happy to share the excel sheets if that's helpful.

Thanks!

**Comment by niflylab** [comment]
Hi Alisa,

Can you please help this? Thank you!

Best, 
Lina Ni

—————————————————
Lina Ni, PhD
Associate Professor
School of Neuroscience
Virginia Tech
Steger Hall, Room 283
(540)232-8463
***@***.***
http://www.ni.neuroscience.vt.edu

**Comment by Eddymorphling** [comment]
Hello,
I was wondering if someone could help me with this issue? Thank you.

**Comment by niflylab** [comment]
Hi Alisa,

Can you please help? Thank you!

Best, 
Lina Ni

—————————————————
Lina Ni, PhD
Associate Professor
School of Neuroscience
Virginia Tech
Steger Hall, Room 283
(540)232-8463
***@***.***
http://www.ni.neuroscience.vt.edu

**Comment by niflylab** [comment]
Please also check the detailed information from this article: doi: 10.3791/64953

The video may help!

Best, 
Lina Ni

—————————————————
Lina Ni, PhD
Associate Professor
School of Neuroscience
Virginia Tech
Steger Hall, Room 283
(540)232-8463
***@***.***
http://www.ni.neuroscience.vt.edu

**Comment by Eddymorphling** [comment]
Hi, thank you for the help! I did check the video, but am having trouble using the plugin. I am not sure if Alisa can see your email as Github may not be redirecting it.

**Comment by niflylab** [comment]
I included Alisa’s email. Thank you!Best,LinaOn Jul 31, 2023, at 6:09 PM, Praveen ***@***.***> wrote:﻿
Hi, thank you for the help! I did check the video, but am having trouble using the plugin. I am not sure if Alisa can see your email as Github may not be redirecting it.

**Comment by AlisaOmel** [comment]
Hi, 

I cannot see the email to contact since GitHub is blocking it. Could you please share the excel files with me here?

**Comment by niflylab** [comment]
Thank you, Alisa!

Best, 
Lina Ni

—————————————————
Lina Ni, PhD
Associate Professor
School of Neuroscience
Virginia Tech
Steger Hall, Room 283
(540)232-8463
***@***.***
http://www.ni.neuroscience.vt.edu

**Comment by niflylab** [comment]
Hi,

Can you please use an email to talk to Alisa which might be easier? Her email address is: ***@***.*** ***@***.***>. Thank you!

Best, 
Lina Ni

—————————————————
Lina Ni, PhD
Associate Professor
School of Neuroscience
Virginia Tech
Steger Hall, Room 283
(540)232-8463
***@***.***
http://www.ni.neuroscience.vt.edu

**Comment by Eddymorphling** [comment]
**EDIT** - I cant see her email as Github is blocking it.
Hi, Thanks for reaching out. I was able to make some progress using the plugin. I am now able to read the excel sheets, made an error naming the files.

Now when TACI runs it only runs the dF/F0 analysis only only the initial time points. Haven't been able to figure out why. Could you pleas have a look at the excel sheets attached here to see if everything is done properly? Thank you.

[TACI.zip](https://github.com/niflylab/TACI_CalciumImagingPlugin/files/12233991/TACI.zip)

**Comment by niflylab** [comment]
Alisa will help you. 

Hi Alisa, can you please have a look? If you cannot see the attached file, please let me know. Thank you!

Best, 
Lina Ni

—————————————————
Lina Ni, PhD
Associate Professor
School of Neuroscience
Virginia Tech
Steger Hall, Room 283
(540)232-8463
***@***.***
http://www.ni.neuroscience.vt.edu

**Comment by AlisaOmel** [comment]
Hello,

One thing I am noticing is that multiple tracks are assigned to the same time point. This gives me the impression that there are multiple neurons/dots being tracked. Each "neuron" should have it's own .csv. If you split the dataset you sent by the TRACK_ID, there are 360 frames per track. There is a bug in the code that improperly treats T positions that are custom and not positive integers from 0 to an integer in increments of 1. Thanks for bringing this to our attention. For now, you can switch the labels of the FRAME column and the POSITION_T column. Unfortunately you may have to edit the column in the results and re-plot if the 30 second increment is important to be in the figure. Please see the update I made to your files. Again I only used track 0 and 1 and there would be many more neurons in this folder, and I switched the labels for POSITION_T and FRAME.

Let me know if you have any more questions, and if you would like to have a short zoom meeting. If you need to contact us directly, so that we have your information, please see the Affiliations section of this [paper](https://pubmed.ncbi.nlm.nih.gov/36591984/), and email Lina Ni.

Best,
Alisa

[TACI_update.zip](https://github.com/niflylab/TACI_CalciumImagingPlugin/files/12234367/TACI_update.zip)

**Comment by Eddymorphling** [comment]
Thank you for the promt response. I will try the work flow that you have suggested.
